farm_asset_termination.settings:
  type: config_object
  label: 'farmOS Asset Termination settings'
  mapping:
    category:
      type: string
      label: 'Termination category id'
    default_termination_log_types:
      type: sequence
      label: 'Default termination log types'
      sequence:
        type: string
        label: 'Log type id'
    enforce_default_termination_log_types:
      type: boolean
      label: 'Enforce default termination log types'
